project:
  type: website
  output-dir: docs
  


website:
  title: "My Blog"
  site-url: https://ruboerner.github.io/Blog
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ruboerner
      - icon: twitter
        href: https://twitter.com/ruboerner
      - icon: rss
        href: index.xml
format:
  html:
    theme: spacelab
    css: styles.css

editor: visual

