project:
  type: website

website:
  title: "My Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ruboerner
      - icon: twitter
        href: https://twitter.com/ruboerner
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

